# Generated by Django 5.1.4 on 2025-01-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
