# Generated by Django 5.1.4 on 2025-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_question_answer_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_choice',
            field=models.BooleanField(default=True),
        ),
    ]
